ATAYEB/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),

    path('', include('core.urls')),
    path('', include('blog.urls')),
    # path('', include('events.urls')),
    path('', include('recipes.urls')),
    path('', include('user.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'blog'

urlpatterns = [
    path('submit-post/', SubmitBlogPost, name='submit-post'),
    path('blog/', PostListView.as_view(), name='blog'),
    path('blog/<int:pk>', PostDetailsView.as_view(),
         name='blog-single'),

    path('blog/<int:pk>/delete', PostDeleteView.as_view(), name='blog-delete'),
    path('blog/<int:pk>/update', PostUpdateView.as_view(), name='blog-update'),
    path('blog/<int:id>/addcomment', AddPostCommentView, name='blog-comment'),
    path("search", SearchBlog, name='search'),
    path('archive/', BlogIndexView, name='archive'),
]

recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


app_name = 'recipes'
urlpatterns = [
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('recipes/<int:pk>', RecipeDetailsView.as_view(), name='recipe-single'),
    path('recipes/<int:pk>/update', RecipeUpdateView.as_view(), name='recipe-update'),
    path('recipes/<int:pk>/steps/update', RecipeInstructionUpdateView.as_view(), name='recipe-steps-update'),
    path('recipes/<int:pk>/ingredient/update', RecipeIngredientsUpdateView.as_view(), name='recipe-ingredient-update'),
    path('recipes/<int:pk>/delete', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipes/<int:pk>/pdf/', ExportToPDFView.as_view(), name='recipe-pdf'),
    path('recipes/<int:id>/addcomment', AddCommentView, name='recipe-comment'),
    path('recipes/<int:id>/bookmark', BookmarkRecipeView, name='recipe-bookmark'),
    path('submit-recipe/', SubmitRecipeView, name='submit-recipe'),
    path('recipe-index/', RecipeIndexView, name='recipe-index'),
    path("search", SearchRecipes, name='search'),
]

recipes/views.py
import re
import json
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from django_renderpdf.views import PDFView
from user.models import Profile

from recipes.models import (Bookmarks, Ingredient, IngredientCategory, Recipe,
                            RecipeCategory, RecipeComment, RecipeIngredient,
                            RecipeInstruction, RecipeNutritionFacts, Tag)


class RecipeListView(ListView):
    paginate_by = 16
    model = Recipe
    template_name = "recipes/recipes.html"
    context_object_name = "recipes"


class RecipeDetailsView(DetailView):
    model = Recipe
    template_name = "recipes/recipe-single.html"
    context_object_name = "recipe"

    def get_context_data(self, **kwargs):
        context = super(RecipeDetailsView, self).get_context_data(**kwargs)

        ingredents_qs = RecipeIngredient.objects.filter(
            recipe=context['recipe'].id).order_by('ingredient__category')
        context['ingredents'] = [*ingredents_qs]

        instructions_qs = RecipeInstruction.objects.filter(
            recipe=context['recipe'].id
        ).order_by('order')
        context['instructions'] = [*instructions_qs]

        comments_qs = RecipeComment.objects.filter(
            recipe=context['recipe'].id).order_by('comment_date')
        context['comments'] = [*comments_qs]

        related_products_qs = Recipe.objects.filter(
            category=context['recipe'].category).order_by('date_created')[:5]
        context['related_recipes'] = [*related_products_qs]

        related_nutration_facts_qs = RecipeNutritionFacts.objects.filter(
            recipe=context['recipe'].id
        )
        context['nutration_facts'] = [*related_nutration_facts_qs]
        feature_list = re.split("', '|\['|']|''",  context['recipe'].tags)
        le = len(feature_list)-1
        feature_list_new = []
        for z in range(1, le):
            feature_list_new.append(feature_list[z])
        context['tags_list'] = feature_list_new
        return context


class ExportToPDFView(PDFView):
    template_name = 'recipes/pdf-view.html'
    prompt_download = True

    @property
    def download_name(self) -> str:
        return f"recipe{self.kwargs['pk']}.pdf"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        recipe = Recipe.objects.get(id=kwargs['pk'])
        context['recipe'] = recipe

        ingredents_qs = RecipeIngredient.objects.filter(
            recipe=context['recipe'].id).order_by('ingredient__category')
        context['ingredents'] = [*ingredents_qs]

        instructions_qs = RecipeInstruction.objects.filter(
            recipe=context['recipe'].id
        ).order_by('order')
        context['instructions'] = [*instructions_qs]

        related_nutration_facts_qs = RecipeNutritionFacts.objects.filter(
            recipe=context['recipe'].id
        )
        context['nutration_facts'] = [*related_nutration_facts_qs]
        return context


@login_required
def AddCommentView(request, id):
    comment = request.POST['comment']
    recipe = Recipe.objects.get(id=id)
    author = Profile.objects.get(user=request.user)
    new_comment = RecipeComment.objects.create(
        body=comment, recipe=recipe, author=author)
    new_comment.save()
    return redirect("recipes:recipe-single", pk=recipe.id)


def RecipeIndexView(request):
    context = {}
    data = {}
    categories = RecipeCategory.objects.all()
    for category in categories:
        recipes = Recipe.objects.filter(category=category)
        data[category] = [*recipes]
    context["data"] = data
    return render(request, "recipes/recipe-index.html", context)


@login_required
def SubmitRecipeView(request):
    if request.method == 'POST':
        # author
        recipe_author = Profile.objects.get(user=request.user)
        recipe_image = request.FILES["recipeImage"]
        recipe_name = request.POST.get('name')
        recipe_feeds_up_to = request.POST.get('feeds_up_to')
        recipe_prep_time = request.POST.get('prep_time')
        recipe_description = request.POST.get('description')

        # category
        recipe_category = RecipeCategory.objects.get_or_create(
            name=request.POST['category'])[0]

        # # tags
        recipe_tags = []
        tags_input = request.POST.get('tags-array')
        split_features = list(tags_input.split(','))
        recipe_tags = [Tag.objects.get_or_create(
            name=item)[0].name for item in split_features]

        for item in recipe_tags:
            Tag.objects.get_or_create(name=item)

        # # create recipe item
        recipe = Recipe.objects.create(
            name=recipe_name, category=recipe_category,
            description=recipe_description, feeds_up_to=recipe_feeds_up_to,
            prep_time=recipe_prep_time, author=recipe_author,
            image=recipe_image, tags=[*recipe_tags])

        # create instructions
        steps_input = str(request.POST['steps-array'])
        steps_list = [x.strip() for x in steps_input.split(',')]
        order = 1
        for item in steps_list:
            RecipeInstruction.objects.create(
                order=order, description=item, recipe=recipe)
            order += 1

        # # create ingredianets
        ingredients_input = json.loads(request.POST['ing-array'])

        for item in ingredients_input:
            ingredient_cat = item[0]
            ingredient_name = item[1]
            ingredient_quantity = item[2]
            ingredient_unit = item[3]
            cat = IngredientCategory.objects.get(name=ingredient_cat)
            ing = Ingredient.objects.get_or_create(
                name=ingredient_name, category=cat)
            RecipeIngredient.objects.create(
                recipe=recipe, ingredient=ing[0], quantity=ingredient_quantity, unit=ingredient_unit)

        # create nutration facts
        # if request.POST.get('totalFatA') and request.POST.get('totalFatP'):
        #     fact1 = RecipeNutritionFacts.objects.create(recipe=recipe, element="اجمالي الدهون", quantity=request.POST.get(
        #         'totalFatA'), daily_percent=request.POST.get('totalFatP'))
        #     fact1.save()

        # if request.POST.get('mealSizeA') and request.POST.get('mealSizeP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="حجم الوجبة", quantity=request.POST.get(
        #         'mealSizeA'), daily_percent=request.POST.get('mealSizeP'))

        # if request.POST.get('postaiumA') and request.POST.get('postaiumP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="البوتاسيوم", quantity=request.POST.get(
        #         'postaiumA'), daily_percent=request.POST.get('postaiumP'))

        # if request.POST.get('sugerA') and request.POST.get('sugerP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="السكر", quantity=request.POST.get(
        #         'sugerA'), daily_percent=request.POST.get('sugerP'))

        # if request.POST.get('protienA') and request.POST.get('protienP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="البروتين", quantity=request.POST.get(
        #         'protienA'), daily_percent=request.POST.get('protienP'))

        # if request.POST.get('fats3A') and request.POST.get('fats3P'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="الدهون المتحولة", quantity=request.POST.get(
        #         'fats3A'), daily_percent=request.POST.get('fats3P'))

        # if request.POST.get('carbA') and request.POST.get('carbP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="اجمالي الكربوهيدرات", quantity=request.POST.get(
        #         'carbA'), daily_percent=request.POST.get('carbP'))

        # if request.POST.get('fatsA') and request.POST.get('fatsP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="الدهون المشبعة", quantity=request.POST.get(
        #         'fatsA'), daily_percent=request.POST.get('fatsP'))

        # if request.POST.get('fats1A') and request.POST.get('fats1P'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="الدهون الأحادية غير المشبعة", quantity=request.POST.get(
        #         'fats1A'), daily_percent=request.POST.get('fats1P'))

        # if request.POST.get('fats2A') and request.POST.get('fats2P'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="دهون غير مشبعة", quantity=request.POST.get(
        #         'fats2A'), daily_percent=request.POST.get('fats2P'))

        # if request.POST.get('sodiumA') and request.POST.get('sodiumP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="صوديوم", quantity=request.POST.get(
        #         'sodiumA'), daily_percent=request.POST.get('sodiumP'))

        # if request.POST.get('fibersA') and request.POST.get('fibersP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="ألياف", quantity=request.POST.get(
        #         'cfibersAalA'), daily_percent=request.POST.get('fibersP'))

        # if request.POST.get('colestrolA') and request.POST.get('colestrolP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="الكوليسترول", quantity=request.POST.get(
        #         'colestrolA'), daily_percent=request.POST.get('colestrolP'))

        # if request.POST.get('calA') and request.POST.get('calP'):
        #     RecipeNutritionFacts.objects.create(recipe=recipe, element="سعرات حراريه", quantity=request.POST.get(
        #         'calA'), daily_percent=request.POST.get('calP'))

        return redirect("recipes:recipes")

recipes/templates/recipes/confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="head-title">
    <div class="container">
        <h2 class="page-title">حذف الوصفات</h2>
    </div>
    <!-- end container -->
</div>
<!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="card main-card mb-4">
            <h5 class="card-header">تأكيد حذف</h5>
            <div class="card-body clearfix">
                <h6 class="pb-1 mb-3 mt-4">هل أنت متأكد من أنك تريد حذف "{{ object.name }}"؟</h6>
                <form class="float-left" action="#" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-danger mt-3" type="submit" value="حذف"> {# <a class="btn btn-primary mt-3 back-btn" href="{% url 'recipes:recipe-single' object.id %}">تراجع</a>#}
                </form>
            </div>
        </div>

    </div>
    <!-- end container -->
</div>
<!-- end main -->

{% endblock %}

recipes/templates/recipes/recipe-index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="head-title">
    <div class="container">
        <h2 class="page-title">دليل الوصفات</h2>
    </div><!-- end container -->
</div><!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="recipe-index card-columns">
            {% for key, value in data.items %}
            <div class="card">
                <div class="index-box">
                    <div class="index-head">
                        <h3>{{key}}</h3>
                    </div>
                    <div class="index-list">
                        <ul>
                            {% for item in value %}
                            <li>
                                <a href="{% url 'recipes:recipe-single'  item.id %}">{{item}}</a>
                                <span>{{item.prep_time}} دقيقة</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div><!-- end index-list -->
                </div><!-- end index-box -->
            </div><!-- end col -->
            {% endfor %}
        </div><!-- end card colum -->

    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}

recipes/templates/recipes/recipe-single.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="head-title">
    <div class="container">
        <h2 class="page-title">{{recipe.category.name}}</h2>
    </div>
    <!-- end container -->
</div>
<!-- end head-title -->

<div id="main">
    <div class="container">

        <div class="recipe-content">

            <div class="row">
                <div class="col">
                    <div class="recipe-lvl">
                        <span>الفئة : <a href="#">{{recipe.category}}</a></span>
                    </div>
                    <!-- end recipe level -->
                    <div class="recipe-head">
                        <h1 class="recipe-title">{{recipe.name}}</h1>
                        <div class="recipe-auth">
                            <!-- {% if recipe.author.image %}
                            <img src="{{ recipe.author.image.url }}" alt="">
                            {% else %}
                            <img src="{% static 'static/images/content/auth-03.png' %}" alt="recipe author">
                            {% endif%} -->

                            <span> الكاتب : <a href="#">{{recipe.author}}</a></span>
                            <span> تاريخ الاضافة : {{recipe.date_created}} </span>
                        </div>
                        <!-- recipe author -->

                        <div class="recipe-finger">

                            <div class="box-sharing">
                                <!-- <a href="#"><i class="fas fa-print"></i></a>
                                <a href="#"><i class="fas fa-share-alt"></i></a> -->
                                <a href="{% url 'recipes:recipe-bookmark' recipe.id %}"><i class="fas fa-bookmark"></i></a>
                                <a href="{% url 'recipes:recipe-pdf' recipe.id %}"><i class="fas fa-file-pdf"></i></a> {%if request.user.profile == recipe.author %}
                                <a href="{% url 'recipes:recipe-update' recipe.id %}"><i class="fas fa-edit"></i></a>
                                <a href="{% url 'recipes:recipe-delete' recipe.id %}"><i class="fas fa-trash"></i></a> {% endif%}
                            </div>

                            <!-- <div class="recipe-rating">
                                <span>درجة الرضا:<i class="fas fa-star"></i><i class="fas fa-star"></i><i
                                        class="fas fa-star"></i><i class="fas fa-star"></i><i
                                        class="far fa-star"></i></span>
                            </div> -->
                        </div>
                        <!-- end recipe finger -->
                    </div>
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->

            <div class="row">
                <div class="col-md-6">
                    <figure class="recipe-pict">
                        <img src="{{ recipe.image.url }}" alt="Recipe Image">
                    </figure>
                </div>
                <!-- end col -->
                <div class="col-md-6">
                    <div class="detail-desc">
                        <p><strong>الوصف</strong></p>
                        <p>{{recipe.description}}</p>
                    </div>
                    <!-- recipe desc -->
                    <hr>
                    <span>تكفي ل {{recipe.feeds_up_to}} اشخاص </span>
                    <span>وقت التحضير : {{recipe.prep_time}} دقيقة </span>
                    <p>
                        <span>علامات:

                            {% for item in tags_list %}
                            <a href="#">{{item}}</a>
                            {% endfor%}

                        </span>
                    </p>
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
            <div class="space-section"></div>
            <div class="row">
                {% if ingredents %}
                <div class="ingredient col-md-4">
                    <p><strong>المكونات والمقادير</strong></p>

                    <ul>
                        {% for item in ingredents %}

                        <li> <span> {{item.quantity}} {{item.unit}} {{item.ingredient}}</span> <span>
                            {%if request.user.profile == recipe.author %}<a href="{% url 'recipes:recipe-ingredient-update' item.id %}"><i class="fas fa-edit"></i></a>{%endif%}
                        </span>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- end col -->
                {% endif %} {% if instructions %}

                <div class="direction col-md-8">

                    <p><strong>طريقة الإعداد</strong></p>
                    <ol>
                        {% for item in instructions %}
                        <li>
                            <p>{{item.description}} <span>                        
                                {%if request.user.profile == recipe.author %} <a href="{% url 'recipes:recipe-steps-update' item.id %}"><i class="fas fa-edit"></i></a>{% endif %}
                            </span></p>
                        </li>
                        {% endfor %}
                    </ol>
                </div>
                <!-- end col -->
                {% endif %}
            </div>
            <!-- end row -->

            {% if nutration_facts %}
            <!-- <div class="space-section"></div> -->
            <hr>
            <div class="row">
                <div class="col-md-4">
                    <p><strong>حقائق الوصفة الغذائية</strong></p>
                    <table style="width: 100%">
                        {% for item in nutration_facts %}
                        <tr>
                            <td><strong>{{item.element}}</strong></td>
                            <td>{{item.quantity}}</td>
                            <td>{{item.daily_percent}}%</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <!-- end col -->
                <div class="col-md-8">
                    <div class="nutrition-bar">
                        {% for item in nutration_facts %}
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: {{item.daily_percent}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
            {% endif %}
        </div>
        <!-- end recipe content -->
    </div>
    <!-- end container -->
</div>
<!-- end main -->

<div class="related-recipe">
    {% if related_recipes %}
    <div class="container">
        <h3>وصفات ذات علاقة</h3>
        <div class="row">
            {% for recipe in related_recipes%}
            <div class="col-6 col-md-3">
                <div class="recipe-thumb">
                    <img src="{{ recipe.image.url }}" width="100px" height="160px" alt="Recipe Image">
                    <a href="{% url 'recipes:recipe-bookmark' recipe.id %}" class="bookmarker"><i class="fas fa-bookmark"></i></a>
                    <a href="{% url 'recipes:recipe-single'  recipe.id %}" class="view-recipe">عرض الوصفة</a>
                </div>
                <div class="recipe-desc">
                    <h2 class="recipe-title">
                        <a href="{% url 'recipes:recipe-single'  recipe.id %}"> {{recipe.name}} </a>
                    </h2>
                    <p><em> بواسطة {{ recipe.author}} </em></p>
                    <span><i class="fas fa-clock"></i> {{recipe.prep_time}} دقيقة </span>
                </div>
                <!-- end recipe-desc -->
            </div>
            <!-- end col -->
            {% endfor %}
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
    {% endif%}
</div>
<!-- related recipe -->

<div class="recipe-comment">
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="comment-outer">
                    <div id="comments" class="comments-area">
                        <h2 class="comments-title">{{comments|length}} تعليقات على هذه الوصفة</h2>
                        <ol class="comment-list">
                            {% for comment in comments%}
                            <li class="comment">
                                <!-- start comment -->
                                <div class="comment-body">

                                    <figure class="comment-author vcard">
                                        {% if comment.author.image %}
                                        <img src="{{ comment.author.image.url}}" height="150px" width="150px" alt="Author"> {% else %}
                                        <img src="{% static 'images/content/auth-ava.png'%}" alt="Author"> {% endif%}
                                    </figure>
                                    <!-- end comment-author vcard -->

                                    <div class="comment-wrapper">
                                        <div class="comment-meta">
                                            <b class="fn">{{comment.author}}</b>
                                            <!-- <div class="reply">
                                                <a href="#" class="comment-reply-link">إجابة</a>
                                            </div> -->
                                        </div>
                                        <!-- end comment-meta -->
                                        <div class="comment-metadata">
                                            <a href="#">
                                                <time datetime="2019-09-04T18:44:25+00:00">{{comment.comment_date}}
                                                </time>
                                            </a>
                                        </div>
                                        <div class="comment-content">
                                            <p>{{comment.body}}</p>
                                        </div>
                                        <!-- end comment-content -->
                                    </div>
                                    <!-- end comment-wrapper -->

                                </div>
                                <!-- end comment-body -->
                            </li>
                            <!-- end li -->
                            {% endfor %}

                        </ol>
                        <!-- end .comment-list -->
                    </div>
                    <!-- end #comments-area -->
                    {% if user.is_authenticated %}

                    <div id="respond" class="comment-respond">
                        <h2 id="reply-title" class="comment-reply-title"> شارك بالتعليق علي هذه الوصفة</h2>
                        <form class="comment-form" action="{% url 'recipes:recipe-comment' recipe.id %}" method="POST">
                            {% csrf_token %}
                            <!-- <p class="comment-notes">لن يتم مشاركة اي من معلوماتك</p>
                            <p class="comment-form-email">
                                <label for="author">الاسم</label>
                                <span class="required">*</span>
                                <input id="author" type="text" class="input-text" name="author">
                            </p>
                            <p class="comment-form-author">
                                <label for="email">البريد الالكتروني</label>
                                <span class="required">*</span>
                                <input id="email" type="text" class="input-text" name="email">
                            </p> -->
                            <p class="comment-form-comment">
                                <label for="comment">التعليق</label>
                                <textarea name="comment" id="comment" cols="45" rows="5" class="input-text"></textarea>
                            </p>
                            <p class="form-submit">
                                <input class="btn btn-primary" name="submit" type="submit" id="button" value="أضف تعليق">
                            </p>
                        </form>
                        <!-- end #comment-form -->
                    </div>
                    <!-- end comment-respond -->
                    {% endif %}

                </div>
                <!-- end comment-outer -->
            </div>
        </div>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/recipe_update_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="head-title">
    <div class="container">
        <h2 class="page-title">عدل وصفتك</h2>
    </div>
    <!-- end container -->
</div>
<!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="row justify-content-center">
            <div class="submit-recipe col-md-8">
                <!-- <header>
                    <h3>مرحبا بك ..</h3>
                    <p> نشكرك علي مشاركتنا وصفتك</p>
                </header> -->
                <form class="form-group" method="post">{% csrf_token %} {{ form.as_p}}

                    <input type="submit" value="Update">
                </form>
            </div>
            <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end main -->

{% endblock %}

recipes/templates/recipes/recipeingredient_update_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="head-title">
    <div class="container">
        <h2 class="page-title">اضف وصفتك</h2>
    </div>
    <!-- end container -->
</div>
<!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="row justify-content-center">
            <div class="submit-recipe col-md-8">
                <!-- <header>
                    <h3>مرحبا بك ..</h3>
                    <p> نشكرك علي مشاركتنا وصفتك</p>
                </header> -->
                <form class="form-group" method="post">{% csrf_token %} {{ form.as_p}}

                    <input type="submit" value="Update">
                </form>
            </div>
            <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end main -->

{% endblock %}

recipes/templates/recipes/recipeinstructionsteps_update_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="head-title">
    <div class="container">
        <h2 class="page-title">عدل وصفتك</h2>
    </div>
    <!-- end container -->
</div>
<!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="row justify-content-center">
            <div class="submit-recipe col-md-8">
                <!-- <header>
                    <h3>مرحبا بك ..</h3>
                    <p> نشكرك علي مشاركتنا وصفتك</p>
                </header> -->
                <form class="form-group" method="post">{% csrf_token %} {{ form.as_p}}

                    <input type="submit" value="Update">
                </form>
            </div>
            <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end main -->

{% endblock %}