ATAYEB/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),

    path('', include('core.urls')),
    path('', include('blog.urls')),
    # path('', include('events.urls')),
    path('', include('recipes.urls')),
    path('', include('user.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'blog'

urlpatterns = [
    path('submit-post/', SubmitBlogPost, name='submit-post'),
    path('blog/', PostListView.as_view(), name='blog'),
    path('blog/<int:pk>', PostDetailsView.as_view(),
         name='blog-single'),

    path('blog/<int:pk>/delete', PostDeleteView.as_view(), name='blog-delete'),
    path('blog/<int:pk>/update', PostUpdateView.as_view(), name='blog-update'),
    path('blog/<int:id>/addcomment', AddPostCommentView, name='blog-comment'),
    path("search", SearchBlog, name='search'),
    path('archive/', BlogIndexView, name='archive'),
]

recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


app_name = 'recipes'
urlpatterns = [
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('recipes/<int:pk>', RecipeDetailsView.as_view(), name='recipe-single'),
    path('recipes/<int:pk>/update', RecipeUpdateView.as_view(), name='recipe-update'),
    path('recipes/<int:pk>/steps/update', RecipeInstructionUpdateView.as_view(), name='recipe-steps-update'),
    path('recipes/<int:pk>/ingredient/update', RecipeIngredientsUpdateView.as_view(), name='recipe-ingredient-update'),
    path('recipes/<int:pk>/delete', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipes/<int:pk>/pdf/', ExportToPDFView.as_view(), name='recipe-pdf'),
    path('recipes/<int:id>/addcomment', AddCommentView, name='recipe-comment'),
    path('recipes/<int:id>/bookmark', BookmarkRecipeView, name='recipe-bookmark'),
    path('submit-recipe/', SubmitRecipeView, name='submit-recipe'),
    path('recipe-index/', RecipeIndexView, name='recipe-index'),
    path("search", SearchRecipes, name='search'),
]

blog/models.py
from user.models import Profile
from django.db import models
from django.utils import timezone
from django_resized import ResizedImageField


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True,
                            verbose_name='اسم العلامة')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "العلامات"


class PostCategory(models.Model):
    name = models.CharField(max_length=255, unique=True,
                            verbose_name='فئة المنشور')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "فئات المنشور"


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name="عنوان المنشور")
    category = models.ForeignKey(
        PostCategory, on_delete=models.CASCADE, verbose_name='فئة المنشور')
    date_created = models.DateTimeField(
        default=timezone.now, verbose_name='تاريخ الإضافة')
    image = ResizedImageField(null=False, blank=False,
                              default=None,
                              upload_to='post_images/',
                              verbose_name='الصورة')
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name='الكاتب')
    body = models.TextField(verbose_name="المحتوي", blank=True, null=True)
    tags = models.CharField(max_length=300, null=True, blank=True, verbose_name="العلامات")

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = "المنشورات"
        ordering = ('-date_created',)


class PostComment(models.Model):
    body = models.TextField(verbose_name='نص التعليق')
    comment_date = models.DateTimeField(
        default=timezone.now, verbose_name='تاريخ التعليق')
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comment_post', verbose_name='المنشور')
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='comment_author', verbose_name='الكاتب')

    def __str__(self):
        return 'تعليق {} على {}.'.format(self.author, self.post)

    class Meta:
        verbose_name_plural = "التعليقات"
        ordering = ('-comment_date',)

blog/views.py
import re

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import redirect, render
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from user.models import Profile
from django.urls import reverse

from blog.models import Post, PostCategory, PostComment, Tag


class PostListView(ListView):
    paginate_by = 10
    model = Post
    template_name = "blog/blog.html"
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)

        recent_posts_qs = Post.objects.all().order_by('-date_created')[:4]
        context['recent_posts'] = [*recent_posts_qs]

        data = {}
        categories = PostCategory.objects.all()
        for category in categories:
            posts = Post.objects.filter(category=category).count()
            data[category] = posts
        context["index_data"] = data

        context['tags'] = [*Tag.objects.all()]
        return context


class PostDetailsView(DetailView):
    model = Post
    template_name = "blog/blog-single.html"
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super(PostDetailsView, self).get_context_data(**kwargs)

        comments_qs = PostComment.objects.filter(
            post=context['post'].id).order_by('-comment_date')
        context['comments'] = [*comments_qs]

        related_posts_qs = Post.objects.filter(
            category=context['post'].category).order_by('-date_created')[:3]
        context['related_posts'] = [*related_posts_qs]

        recent_posts_qs = Post.objects.all().order_by('-date_created')[:4]
        context['recent_posts'] = [*recent_posts_qs]

        data = {}
        categories = PostCategory.objects.all()
        for category in categories:
            posts = Post.objects.filter(category=category).count()
            data[category] = posts
        context["index_data"] = data

        context['tags'] = [*Tag.objects.all()]

        # handle post tags
        feature_list = re.split("', '|\['|']|''",  context['post'].tags)
        le = len(feature_list)-1
        feature_list_new = []
        for z in range(1, le):
            feature_list_new.append(feature_list[z])
        context['tags_list'] = feature_list_new

        return context


@login_required
def AddPostCommentView(request, id):
    comment = request.POST['comment']
    post = Post.objects.get(id=id)
    author = Profile.objects.get(user=request.user)
    new_comment = PostComment.objects.create(
        body=comment, post=post, author=author)
    new_comment.save()
    return redirect("blog:blog-single", pk=post.id)


def SearchBlog(request):
    keyword = request.GET.get('keyword')
    myposts = Post.objects.filter(title__icontains=keyword)
    return render(request, "blog/blog.html", {'posts': myposts})


def BlogIndexView(request):
    context = {}

    recent_posts_qs = Post.objects.all().order_by('date_created')[:4]
    context['recent_posts'] = [*recent_posts_qs]

    context['tags'] = [*Tag.objects.all()]
    data = {}
    categories = PostCategory.objects.all()
    for category in categories:
        posts = Post.objects.filter(category=category).count()
        data[category] = posts
    context["index_data"] = data

    data = {}
    categories = PostCategory.objects.all()
    for category in categories:
        posts = Post.objects.filter(category=category)
        data[category] = [*posts]
    context["data"] = data
    return render(request, "blog/archive.html", context)


@login_required
def SubmitBlogPost(request):
    if request.method == 'POST':
        # author
        post_author = Profile.objects.get(user=request.user)
        post_image = request.FILES["postImage"]
        post_title = request.POST.get('title')
        post_body = request.POST.get('body')

        # tags
        post_tags = []
        tags_input = request.POST.get('tags-array')
        split_features = list(tags_input.split(','))
        post_tags = [Tag.objects.get_or_create(
            name=item)[0].name for item in split_features]

        for item in post_tags:
            Tag.objects.get_or_create(name=item)

        # category
        category_field = request.POST.get('category')

        if category_field == "other":
            other_category_field = request.POST.get('other_category')
            post_category = PostCategory.objects.get_or_create(
                name=other_category_field)[0]
        else:
            post_category = PostCategory.objects.get(
                name=request.POST.get('category'))

        # create recipe item
        post = Post.objects.create(
            title=post_title, category=post_category, tags=[*post_tags], author=post_author, image=post_image, body=post_body)
        post.save()
        return redirect("blog:blog")

    categories = PostCategory.objects.all()
    context = {}
    context['categories'] = [*categories]
    return render(request, "blog/submit-post.html", context=context)



class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    login_url = 'user:login'
    model = Post
    success_url = '/'
    template_name = 'blog/confirm_delete.html'

    def test_func(self):
        obj = self.get_object()
        if self.request.user.profile == obj.author:
            return True
        return False


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'category', 'image', 'body', 'tags' ]
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse('blog:blog-single', kwargs={'pk': self.object.id})

blog/templates/blog/archive.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div class="head-title">
            <div class="container">
                <h2 class="page-title">الارشيف</h2>
            </div><!-- end container -->
        </div><!-- end head-title -->

        <div id="main">
            <div class="container">
                <div class="row">
                    
                    <div id="primary" class="content-area col-md-8">
                        <div id="content" class="site-content">
                            {% for key, value in data.items %}

                            <h3 class="archive-title">{{key}}</h3>
                            <div class="article-list">
                                <div class="row">
                                    {% for item in value %}

                                    <div class="col-md-2">
                                        <p class="cat-list">{{item.category}}</p>
                                        <div class="entry-date">
                                            <a href="#">
                                                <time class="published" datetime="2019-12-22"
                                                title="December 22, 2019 - 21:12 pm">{{item.date_created|date}} </time>                                            </a>
                                        </div><!-- end entry-date -->
                                    </div>
                                    <div class="col-md-5">
                                        <figure>
                                            <img src="{{item.image.url}}" width="180px" height="180px">
                                        </figure>
                                    </div>
                                    <div class="col-md-5">
                                        <h3>
                                            <a href="{% url 'blog:blog-single' item.id %}">{{item.title}}</a>
                                        </h3>
                                        <a href="{% url 'blog:blog-single' item.id %}" class="readmore"><em>اقرأ المزيد</em></a>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div><!-- end article-list -->
                            {% endfor %}

                            <nav class="pagination-container" aria-label="Page navigation">
                                {% if is_paginated %}
                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item"><a class="page-link"
                                            href="?page={{page_obj.previous_page_number}}">السابق</a>
                                    </li>
                                    {% else %}
                                    <li class="page-item disabled"><a class="page-link" href="#">السابق</a>
                                    </li>
                                    {% endif %}
            
            
                                    {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                    {% endif %}
                                    {% endfor %}
            
                                    {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link"
                                            href="?page={{ page_obj.next_page_number }}">التالي</a></li>
                                    {% else %}
                                    <li class="page-item disabled"><a class="page-link" href="#">التالي</a></li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                            </nav>
                        </div><!-- end content -->
                    </div><!-- end primary -->

                    <div id="secondary" class="col-md-4">

                        <div id="search-2" class="widget widget_search">
                            <div class="widget-title-outer">
                                <h3 class="widget-title">البحث</h3>
                            </div>
                            <div class="searchform">
                                <form action="{% url 'blog:search' %}" method="get">
                                    {% csrf_token %}
                                    <input type="text" class="txt" name="keyword" placeholder="ابحث عن...">
                                    <input type="submit" value="إبحث" class="btn btn-sm">
                                </form>
                            </div><!-- end searchform -->
                        </div><!-- end search widget -->
        
                        <div class="widget post-type-widget">
                            <div class="widget-title-outer">
                                <h3 class="widget-title">أحدث التدوينات</h3>
                            </div>
                            <ul>
                                {% for post in recent_posts %}
                                <li>
                                    <span class="post-category">
                                        <a href="#">{{post.category}}</a>
                                    </span>
                                    <figure class="post-thumbnail">
                                        <a href="{% url 'blog:blog-single'  post.id %}"><img src="{{post.image.url}}"
                                                alt=""></a>
                                    </figure>
                                    <h2 class="post-title">
                                        <a href="{% url 'blog:blog-single'  post.id %}">{{post.title}}</a>
                                    </h2>
                                </li>
                                {% endfor %}
                            </ul>
                        </div><!-- end widget -->
        
                        <div class="widget widget_categories">
                            <div class="widget-title-outer">
                                <h3 class="widget-title">فئات التدوينات</h3>
                            </div>
                            <ul>
                                {% for key, value in index_data.items %}
                                <li>
                                    <a class="float-right" href="#">{{key}}</a>
                                    <span class="float-left">{{value}}</span>
                                </li>
                                {% endfor %}
                            </ul>
                        </div><!-- end widget -->
        
                        <div class="widget">
                            <div class="widget-title-outer">
                                <h3 class="widget-title">علامات التدوينات</h3>
                            </div>
                            <div class="tagcloud">
                                {% for item in tags %}
                                <a href="#">{{item}}</a>
                                {% endfor %}
                            </div>
                        </div><!-- end widget -->
        
                    </div><!-- end #secondary -->
        
                </div><!-- end row -->
            </div><!-- end container -->
        </div><!-- end main -->

{% endblock %}

blog/templates/blog/blog-single.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="head-title">
    <div class="container">
        <h2 class="page-title">تدوينة</h2>
    </div>
    <!-- end container -->
</div>
<!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="row">

            <div id="primary" class="content-area col-md-8">
                <div id="content" class="site-content">

                    <div class="post format-image hentry">

                        <div class="entry-format">
                            <div class="entry-meta">
                                <div class="entry-date">
                                    <a href="#">
                                        <time class="published" datetime="2019-12-22" title="December 22, 2019 - 21:12 pm">{{post.date_created|date}} </time>
                                    </a>
                                </div>
                                <!-- end entry-date -->

                                <div class="social-shares">
                                    {%if request.user.profile == post.author %}
                                    <div class="other-share">
                                        <a href="{% url 'blog:blog-delete' post.id %}"><i class="fas fa-trash"></i></a>
                                        <a href="{% url 'blog:blog-update' post.id %}"><i class="fas fa-edit"></i></a>

                                    </div>
                                    {% endif %}
                                    <!-- end other-share -->
                                </div>
                                <!-- end social-share -->

                            </div>
                            <!-- end entry-meta -->
                        </div>
                        <!-- end entry-format -->

                        <div class="inner">

                            <div class="entry-header">
                                <h1 class="entry-title">
                                    <a href="{% url 'blog:blog-single'  post.id %}"> {{post.title}}</a>

                                </h1>
                                <div class="entry-header">
                                    <span> الناشر : {{post.author}}</span>
                                </div>
                                <!-- end entry-header -->

                            </div>
                            <!-- end entry-header -->
                            <div class="entry-content">

                                <figure class="wp-caption">
                                    <img src="{{post.image.url}}" alt="">
                                </figure>
                                <p>{{post.body}}</p>

                                <p>
                                    <span>الفئات: <a href="#"><em>{{post.category}}</em></a></span><br />
                                    <span>علامات:

                                        {% for item in tags_list %}
                                        <a href="#">{{item}}</a>
                                        {% endfor%}

                                    </span>
                                </p>
                            </div>
                            <!-- end entry-content -->

                        </div>
                        <!-- end inner -->

                    </div>
                    <!-- end format-image hentry -->

                    <div class="author-wrapper">
                        <h2>عن الناشر:</h2>
                        <figure class="author-ava">
                            <img src="{{post.author.image.url}}" height="100px" width="100px" alt="Author">
                        </figure>
                        <div class="author-context">

                            <div class="author-name">
                                <a href="#">{{post.author}}</a>
                            </div>
                            <!-- end auth-name -->

                            <div class="author-content">
                                <p>{{post.author.bio}}</p>
                            </div>

                        </div>
                        <!-- end author-wrapper -->
                    </div>
                    <!-- end author-area -->

                    <div class="related-content">
                        <h2>مواضيع ذات علاقة</h2>
                        <div class="row">
                            {% if related_posts %} {% for post in related_posts%}

                            <div class="col-md-4">
                                <figure>
                                    <img src="{{post.image.url}}" width="200px" height="150px">
                                </figure>
                                <div class="related-title">
                                    <h3><a href="#"> {{post.title}}</a></h3>
                                </div>
                            </div>
                            <!-- end column -->
                            {% endfor %} {% endif %}
                        </div>
                        <!-- end row -->
                    </div>
                    <!-- end related-content -->

                    <div class="comment-outer">
                        <div id="comments" class="comments-area">
                            <h2 class="comments-title">{{comments|length}} تعليقات</h2>
                            <ol class="comment-list">
                                {% for comment in comments%}
                                <li class="comment">
                                    <!-- start comment -->
                                    <div class="comment-body">

                                        <figure class="comment-author vcard">
                                            <img src="{{comment.author.image.url}}" width="100px" height="100px" alt="">
                                        </figure>
                                        <!-- end comment-author vcard -->

                                        <div class="comment-wrapper">
                                            <div class="comment-meta">
                                                <b class="fn">{{comment.author}}</b>
                                            </div>
                                            <!-- end comment-meta -->
                                            <div class="comment-metadata">
                                                <a href="#">
                                                    <time datetime="2019-09-04T18:44:25+00:00">{{comment.comment_date}}
                                                    </time>
                                                </a>
                                            </div>
                                            <div class="comment-content">
                                                <p>{{comment.body}}</p>
                                            </div>
                                            <!-- end comment-content -->
                                        </div>
                                        <!-- end comment-wrapper -->

                                    </div>
                                    <!-- end comment-body -->

                                </li>
                                <!-- end li -->
                                {% endfor %}

                            </ol>
                            <!-- end .comment-list -->
                        </div>
                        <!-- end #comments-area -->

                        {% if user.is_authenticated %}
                        <div id="respond" class="comment-respond">
                            <h2 id="reply-title" class="comment-reply-title"> شارك بالتعليق علي هذا المنشور</h2>
                            <form class="comment-form" action="{% url 'blog:blog-comment' post.id %}" method="POST">
                                {% csrf_token %}
                                <p class="comment-form-comment">
                                    <label for="comment">التعليق</label>
                                    <textarea name="comment" id="comment" cols="45" rows="5" class="input-text"></textarea>
                                </p>
                                <p class="form-submit">
                                    <input class="btn btn-primary" name="submit" type="submit" id="button" value="أضف تعليق">
                                </p>
                            </form>
                            <!-- end #comment-form -->
                        </div>
                        <!-- end comment-respond -->
                        {% endif %}

                    </div>
                    <!-- end comment-outer -->
                </div>
                <!-- end content -->
            </div>
            <!-- end primary -->

            <div id="secondary" class="col-md-4">

                <div id="search-2" class="widget widget_search">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">البحث</h3>
                    </div>
                    <div class="searchform">
                        <form action="{% url 'blog:search' %}" method="get">
                            {% csrf_token %}
                            <input type="text" class="txt" name="keyword" placeholder="ابحث عن...">
                            <input type="submit" value="إبحث" class="btn btn-sm">
                        </form>
                    </div>
                    <!-- end searchform -->
                </div>
                <!-- end search widget -->

                <div class="widget post-type-widget">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">أحدث التدوينات</h3>
                    </div>
                    <ul>
                        {% for post in recent_posts %}
                        <li>
                            <span class="post-category">
                                <a href="#">{{post.category}}</a>
                            </span>
                            <figure class="post-thumbnail">
                                <a href="{% url 'blog:blog-single'  post.id %}"><img src="{{post.image.url}}" alt=""></a>
                            </figure>
                            <h2 class="post-title">
                                <a href="{% url 'blog:blog-single'  post.id %}">{{post.title}}</a>
                            </h2>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- end widget -->

                <div class="widget widget_categories">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">فئات التدوينات</h3>
                    </div>
                    <ul>
                        {% for key, value in index_data.items %}
                        <li>
                            <a class="float-right" href="#">{{key}}</a>
                            <span class="float-left">{{value}}</span>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- end widget -->

                <div class="widget">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">علامات التدوينات</h3>
                    </div>
                    <div class="tagcloud">
                        {% for item in tags %}
                        <a href="#">{{item}}</a> {% endfor %}
                    </div>
                </div>
                <!-- end widget -->

                <!-- <div class="widget">
                    <a href="#"><img src="{% static 'recipes/images/content/banner.png' %}" alt="Banner"></a>
                </div>

                <div class="widget">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">Our Facebook Page</h3>
                    </div>
                    <iframe
                        src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FFacebookDevelopers&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true"></iframe>
                </div>end widget -->

            </div>
            <!-- end #secondary -->

        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>
<!-- end main -->

{% endblock %}