ATAYEB/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),

    path('', include('core.urls')),
    path('', include('blog.urls')),
    # path('', include('events.urls')),
    path('', include('recipes.urls')),
    path('', include('user.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'blog'

urlpatterns = [
    path('submit-post/', SubmitBlogPost, name='submit-post'),
    path('blog/', PostListView.as_view(), name='blog'),
    path('blog/<int:pk>', PostDetailsView.as_view(),
         name='blog-single'),

    path('blog/<int:pk>/delete', PostDeleteView.as_view(), name='blog-delete'),
    path('blog/<int:pk>/update', PostUpdateView.as_view(), name='blog-update'),
    path('blog/<int:id>/addcomment', AddPostCommentView, name='blog-comment'),
    path("search", SearchBlog, name='search'),
    path('archive/', BlogIndexView, name='archive'),
]

recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


app_name = 'recipes'
urlpatterns = [
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('recipes/<int:pk>', RecipeDetailsView.as_view(), name='recipe-single'),
    path('recipes/<int:pk>/update', RecipeUpdateView.as_view(), name='recipe-update'),
    path('recipes/<int:pk>/steps/update', RecipeInstructionUpdateView.as_view(), name='recipe-steps-update'),
    path('recipes/<int:pk>/ingredient/update', RecipeIngredientsUpdateView.as_view(), name='recipe-ingredient-update'),
    path('recipes/<int:pk>/delete', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipes/<int:pk>/pdf/', ExportToPDFView.as_view(), name='recipe-pdf'),
    path('recipes/<int:id>/addcomment', AddCommentView, name='recipe-comment'),
    path('recipes/<int:id>/bookmark', BookmarkRecipeView, name='recipe-bookmark'),
    path('submit-recipe/', SubmitRecipeView, name='submit-recipe'),
    path('recipe-index/', RecipeIndexView, name='recipe-index'),
    path("search", SearchRecipes, name='search'),
]

user/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from user.views import AcceptInviteView

from .views import *

app_name = 'user'
urlpatterns = [
    path('my-account/', MyProfileView, name='my-account'),

    path('profile_update/', profile_update, name='profile_update'),


    path('invite-form/', TemplateView.as_view(template_name='user/invite_form.html'),
         name='invite_form'),

    path('invite/', invite_friend, name='invite_friend'),
    path(r'^invitations/accept-invite/(?P<key>\w+)/?$',
         AcceptInviteView.as_view(), name='accept-invite'),

]

user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django_resized import ResizedImageField


class Profile(models.Model):
    image = ResizedImageField(
        default=None, upload_to='profile_images/')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=250, blank=True,
                           default="Contributer User")

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwarg):
    if kwarg['created']:
        profile = Profile.objects.create(user=kwarg['instance'])
    


post_save.connect(create_profile, sender=User)

user/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile


class UserCreationForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم', max_length=30,
                               help_text='اسم المستخدم يجب ألا يحتوي على مسافات.')
    email = forms.EmailField(label='البريد الإلكتروني')
    first_name = forms.CharField(label='الاسم الأول')
    last_name = forms.CharField(label='الاسم الأخير')
    password1 = forms.CharField(
        label='كلمة المرور', widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(
        label='تأكيد كلمة المرور', widget=forms.PasswordInput(), min_length=8)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('كلمة المرور غير متطابقة')
        return cd['password2']

    def clean_username(self):
        cd = self.cleaned_data
        if User.objects.filter(username=cd['username']).exists():
            raise forms.ValidationError('يوجد مستخدم مسجل بهذا الاسم.')
        return cd['username']


class LoginForm(forms.ModelForm):
    username = forms.CharField(label='اسم المستخدم')
    password = forms.CharField(
        label='كلمة المرور', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الأول')
    last_name = forms.CharField(label='الاسم الأخير')
    email = forms.EmailField(label='البريد الإلكتروني')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)

user/views.py
from allauth.account.models import EmailAddress
from allauth.account.signals import user_signed_up
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from invitations.adapters import get_invitations_adapter
from invitations.app_settings import app_settings
from invitations.models import Invitation
from invitations.signals import invite_accepted
from invitations.utils import get_invitation_model
from invitations.views import AcceptInvite
from recipes.models import Recipe, Bookmarks
from blog.models import Post, PostCategory , Tag
from user.models import Profile
from .forms import ProfileUpdateForm, UserCreationForm, UserUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password1'])
            new_user.save()
            messages.success(
                request, f'تهانينا {new_user} لقد تمت عملية التسجيل بنجاح.')
            return redirect('user:login')
    else:
        form = UserCreationForm()
    return render(request, 'user/signup.html', {
        'title': 'التسجيل',
        'form': form,
    })


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('user:profile')
        else:
            messages.warning(
                request, 'هناك خطأ في اسم المستخدم أو كلمة المرور.')

    return render(request, 'user/login.html', {
        'title': 'تسجيل الدخول',
    })


def logout_user(request):
    logout(request)
    return render(request, 'user/logout.html', {
        'title': 'تسجيل الخروج'
    })


class ProfileDetail(LoginRequiredMixin, SingleObjectMixin, ListView):
    # ORIGINAL ATTRIBUTES
    login_url = 'user:login'
    model = User
    template_name = 'user/profile.html'
    paginate_by = 10
    paginate_orphans = 10

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(User, username=self.request.user)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)


@login_required(login_url='user:login')
def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            messages.success(
                request, 'تم تحديث الملف الشخصي.')
            return redirect('user:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'title': 'تعديل الملف الشخصي',
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'user/profile_update.html', context)


# ---------------- INVITATIONS --------------------------
def invite_friend(request):
    # inviter argument is optional
    Invitation = get_invitation_model()
    invite = Invitation.create('email1@example1.com', inviter=request.user)
    invite.send_invitation(request)
    return redirect(app_settings.SIGNUP_REDIRECT)


# django-invitations https://gist.github.com/nsomaru/53d0caf0981b56d57d77649b29c8cd1d
class AcceptInviteView(AcceptInvite):
    def post(self, *args, **kwargs):
        self.object = invitation = self.get_object()

        # Compatibility with older versions: return an HTTP 410 GONE if there
        # is an error. # Error conditions are: no key, expired key or
        # previously accepted key.
        if app_settings.GONE_ON_ACCEPT_ERROR and \
                (not invitation or
                 (invitation and (invitation.accepted or
                                  invitation.key_expired()))):
            return HttpResponse(status=410)

        # No invitation was found.
        if not invitation:
            # Newer behavior: show an error message and redirect.
            get_invitations_adapter().add_message(
                self.request,
                messages.ERROR,
                'invitations/messages/invite_invalid.txt')
            return redirect(app_settings.LOGIN_REDIRECT)

        # The invitation was previously accepted, redirect to the login
        # view.
        if invitation.accepted:
            get_invitations_adapter().add_message(
                self.request,
                messages.ERROR,
                'invitations/messages/invite_already_accepted.txt',
                {'email': invitation.email})
            # Redirect to login since there's hopefully an account already.
            return redirect(app_settings.LOGIN_REDIRECT)

        # The key was expired.
        if invitation.key_expired():
            get_invitations_adapter().add_message(
                self.request,
                messages.ERROR,
                'invitations/messages/invite_expired.txt',
                {'email': invitation.email})
            # Redirect to sign-up since they might be able to register anyway.
            return redirect(app_settings.SIGNUP_REDIRECT)

        get_invitations_adapter().stash_verified_email(
            self.request, invitation.email)

        get_invitations_adapter().add_message(
            self.request,
            messages.SUCCESS,
            'invitations/messages/invite_accepted.txt',
            {'email': invitation.email})

        return redirect(app_settings.SIGNUP_REDIRECT)


@receiver(user_signed_up)
def accept_invite(sender, request, user, **kwargs):
    # Traverse from the user to verified email addresses. It is possible for a
    # user to already have multiple email addresses if they typed in a different
    # email after accepted the invite. In this case, the user will have two
    # emails, but only one will be verified.
    addresses = EmailAddress.objects.filter(user=user, verified=True) \
        .values_list('email', flat=True)
    # Check if any invites exist for this address and were accepted.
    invites = Invitation.objects.filter(email__in=addresses)
    if invites:
        # Mark all these invites as accepted.
        invites.update(accepted=True)
        for invite in invites:
            # Note that this doesn't send it with a request.
            invite_accepted.send(sender=Invitation, email=invite.email)

        # Figure out if you care if there are multiple invites here


@login_required
def MyProfileView(request):
    profile = Profile.objects.get(user=request.user)
    recipes = Recipe.objects.filter(author=profile)
    bookmarks = Bookmarks.objects.get(profile=profile).recipes.all()
    posts = Post.objects.filter(author=profile)
    context = {}
    context['profile'] = profile
    context['recipes'] = recipes
    if bookmarks != None:
        context['bookmarks'] = bookmarks
        
    if posts != None:
        context['posts'] = posts

    
    recent_posts_qs = Post.objects.all().order_by('date_created')[:4]
    context['recent_posts'] = [*recent_posts_qs]

    context['tags'] = [*Tag.objects.all()]

    data = {}
    categories = PostCategory.objects.all()
    for category in categories:
        posts = Post.objects.filter(category=category).count()
        data[category] = posts
    context["index_data"] = data
    return render(request, "user/my-account.html", context)

user/templates/user/invite_form.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

    <div class="head-title">
        <div class="container">
            <h2 class="page-title">دعوة صديق</h2>
        </div><!-- end container -->
    </div><!-- end head-title -->

    <div id="main">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6">
                    <div class="acc-box equal">


{#                        <h4 class="title">{% trans "Invite" %}</h4>#}
{#                        <span class="alert alert-info">{% trans "Please add an email below. The user will receive an email with instructions." %}</span>#}

                        <span>أدخل البريد الإلكتروني لمن تريد دعوته، وسيتلقى رسالة تخوله بالاشتراك.</span>
                        <br>

                        <form id="invite-form" method="POST" action="{% url 'invitations:send-invite' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" name="email" id="id_email" value="{{ form.email.value }}"
                                       class="form-control validate-email" placeholder="{% trans 'Email' %}">
                            </div>
                            <div class="form-group">
                                {% for error in form.email.errors %}
                                    <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                                {{ success_message }}
                            </div>
                            <input type="submit" value="أرسل الدعوة" class="btn btn-primary generic-ajax-submit">
                        </form>

                    </div><!-- end acc-box -->
                </div><!-- end col -->
            </div>
        </div><!-- end container -->
    </div><!-- end main -->

{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="head-title">
        <div class="container">
            <h2 class="page-title">الدخول إلى الموقع</h2>
        </div><!-- end container -->
    </div><!-- end head-title -->

    <div id="main">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6">
                    <div class="acc-box equal">
{#                        <h2>الدخول</h2>#}
                        <span>إذا لم تكن عضوا في الموقع من قبل يمكنك الاشتراك <a href="{% url 'user:signup' %} ">من هنا</a></span>
                        <br>
                        <form>
                            <div class="form-group">
                                <label for="InputEmailAcc1">البريد الالكتروني *</label>
                                <input type="email" class="form-control" id="InputEmailAcc1" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">كلمة المرور *</label>
                                <input type="password" class="form-control" id="exampleInputPassword1"
                                       placeholder="Password">
                            </div>
                            <div class="form-check">
                                <label class="form-check-label" for="rememberCheck">تذكرني  </label>
                                <input type="checkbox" class="form-check-input" id="rememberCheck">
                            </div>
                            <button type="submit" class="btn btn-primary">دخول</button>
                            <span class="float-end">نسيت كلمة المرور؟ <a href="#">إضغط هنا</a></span>
                        </form>
                    </div><!-- end acc-box -->
                </div><!-- end col -->
            </div>
        </div><!-- end container -->
    </div><!-- end main -->

{% endblock %}

user/templates/user/my-account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="head-title">
    <div class="container">
        <h2 class="page-title">الملف الشخصي</h2>
    </div><!-- end container -->
</div><!-- end head-title -->

<div id="main">
    <div class="container">
        <div class="row">
            <div id="primary" class="content-area col-md-8">
                <div id="content" class="site-content">

                    <div class="profile-details">
                        <figure class="profile-ava">
                            {% if profile.image %}
                                <img src="{{ profile.image.url}}" height="150px" width="150px" alt="Author">
                            {% else%}
                                <img src="{% static 'images/content/auth-ava.png'%}" alt="Author">
                            {% endif %}

                        </figure>
                        <div class="profile-context">
                            <div class="profile-name">
                                <h3>{{profile.user}}</h3>
                            </div>
                            <div class="profile-content">
                                <p> {{profile.bio}} </p>
                            </div>
                            <!-- <div class="profile-socmed">
                                <a href="#"><i class="fab fa-facebook-square"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                                <a href="#"><i class="fab fa-pinterest"></i></a>
                                <a href="#"><i class="fab fa-linkedin"></i></a>
                                <a href="#"><i class="fas fa-envelope"></i></a>
                            </div> -->
                        </div><!-- end profile-context -->
                    </div><!-- end profile-details -->

                    <div class="my-content">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="recipe-tab" data-toggle="tab" href="#recipe" role="tab"
                                    aria-controls="recipe" aria-selected="false">وصفاتي
                                    <strong>({{recipes.count}})</strong></a>
                            </li>
                            {% if bookmarks %}
                            <li class="nav-item">
                                <a class="nav-link" id="bookmark-tab" data-toggle="tab" href="#bookmark" role="tab"
                                    aria-controls="bookmark" aria-selected="false">وصفاتي المفضلة
                                    <strong> ({{bookmarks.count}}) </strong></a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" id="article-tab" data-toggle="tab" href="#article" role="tab"
                                    aria-controls="article" aria-selected="true">تدويناتي
                                    <strong>({{posts.count}})</strong></a>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade  show active" id="recipe" role="tabpanel"
                                aria-labelledby="recipe-tab">
                                {% if recipes %}
                                <div class="row">
                                    {% for recipe in recipes%}
                                    <div class="col-4">
                                        <div class="recipe-thumb">
                                            <img src="{{ recipe.image.url }}" alt="Recipe Image">
                                            <a href="{% url 'recipes:recipe-bookmark' recipe.id %}" class="bookmarker"><i class="fas fa-bookmark"></i></a>
                                            <a href="{% url 'recipes:recipe-single'  recipe.id %}"
                                                class="view-recipe">عرض الوصفة</a>
                                        </div>
                                        <div class="recipe-desc">
                                            <h2 class="recipe-title">
                                                <a href="{% url 'recipes:recipe-single'  recipe.id %}"> {{recipe.name}}
                                                </a>
                                            </h2>
                                            <p><em> بواسطة {{ recipe.author}} </em></p>
                                            <span><i class="fas fa-clock"></i> {{recipe.prep_time}} دقيقة </span>
                                        </div><!-- end recipe-desc -->
                                    </div><!-- end col -->
                                    {% endfor %}
                                </div><!-- end row -->
                                {% else %}
                                <div class="row justify-content-center">
                                    <h2>لم تقم باضافة وصفات بعد .. </h2>
                                </div>
                                {% endif%}
                            </div><!-- end tab -->
                            {% if bookmarks %}
                            <div class="tab-pane fade" id="bookmark" role="tabpanel" aria-labelledby="bookmark-tab">
                                <div class="row">
                                    {% for recipe in bookmarks %}
                                    <div class="col-4">
                                        <div class="recipe-thumb">
                                            <img src="{{ recipe.image.url }}" alt="Recipe Image">
                                            <a href="{% url 'recipes:recipe-single'  recipe.id %}"
                                                class="view-recipe">عرض الوصفة</a>
                                        </div>
                                        <div class="recipe-desc">
                                            <h2 class="recipe-title">
                                                <a href="{% url 'recipes:recipe-single'  recipe.id %}"> {{recipe.name}}
                                                </a>
                                            </h2>
                                            <p><em> بواسطة {{ recipe.author}} </em></p>
                                            <span><i class="fas fa-clock"></i> {{recipe.prep_time}} دقيقة </span>
                                        </div><!-- end recipe-desc -->
                                    </div><!-- end col -->
                                    {% endfor %}
                                </div><!-- end row -->
                            </div>
                            {% endif %}
                            <div class="tab-pane fade" id="article" role="tabpanel" aria-labelledby="article-tab">
                                <div class="article-list">
                                    <div class="row">
                                        {% for item in posts %}
    
                                        <div class="col-md-2">
                                            <p class="cat-list">{{item.category}}</p>
                                            <div class="entry-date">
                                                <a href="#">
                                                    <time class="published" datetime="2019-12-22"
                                                    title="December 22, 2019 - 21:12 pm">{{item.date_created|date}} </time>                                            </a>
                                            </div><!-- end entry-date -->
                                        </div>
                                        <div class="col-md-5">
                                            <figure>
                                                <img src="{{item.image.url}}" width="180px" height="180px">
                                            </figure>
                                        </div>
                                        <div class="col-md-5">
                                            <h3>
                                                <a href="{% url 'blog:blog-single' item.id %}">{{item.title}}</a>
                                            </h3>
                                            <a href="{% url 'blog:blog-single' item.id %}" class="readmore"><em>اقرأ المزيد</em></a>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div><!-- end article-list -->
                                
                            </div>
                        </div>
                    </div><!-- end my-content -->

                </div><!-- end content -->
            </div><!-- end primary -->

            <div id="secondary" class="col-md-4">

                <div id="search-2" class="widget widget_search">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">البحث</h3>
                    </div>
                    <div class="searchform">
                        <form action="{% url 'blog:search' %}" method="get">
                            {% csrf_token %}
                            <input type="text" class="txt" name="keyword" placeholder="ابحث عن...">
                            <input type="submit" value="إبحث" class="btn btn-sm">
                        </form>
                    </div><!-- end searchform -->
                </div><!-- end search widget -->

                <div class="widget post-type-widget">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">أحدث التدوينات</h3>
                    </div>
                    <ul>
                        {% for post in recent_posts %}
                        <li>
                            <span class="post-category">
                                <a href="#">{{post.category}}</a>
                            </span>
                            <figure class="post-thumbnail">
                                <a href="{% url 'blog:blog-single'  post.id %}"><img src="{{post.image.url}}"
                                        alt=""></a>
                            </figure>
                            <h2 class="post-title">
                                <a href="{% url 'blog:blog-single'  post.id %}">{{post.title}}</a>
                            </h2>
                        </li>
                        {% endfor %}
                    </ul>
                </div><!-- end widget -->

                <div class="widget widget_categories">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">فئات التدوينات</h3>
                    </div>
                    <ul>
                        {% for key, value in index_data.items %}
                        <li>
                            <a class="float-right" href="#">{{key}}</a>
                            <span class="float-left">{{value}}</span>
                        </li>
                        {% endfor %}
                    </ul>
                </div><!-- end widget -->

                <div class="widget">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">علامات التدوينات</h3>
                    </div>
                    <div class="tagcloud">
                        {% for item in tags %}
                        <a href="#">{{item}}</a>
                        {% endfor %}
                    </div>
                </div><!-- end widget -->

                <div class="widget">
                    <a href="#"><img src="{% static 'recipes/images/content/banner.png' %}" alt="Banner"></a>
                </div>

                <div class="widget">
                    <div class="widget-title-outer">
                        <h3 class="widget-title">Our Facebook Page</h3>
                    </div>
                    <iframe
                        src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2FFacebookDevelopers&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true"></iframe>
                </div><!-- end widget -->

            </div><!-- end #secondary -->

        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}