ATAYEB/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('invitations/', include('invitations.urls', namespace='invitations')),

    path('', include('core.urls')),
    path('', include('blog.urls')),
    # path('', include('events.urls')),
    path('', include('recipes.urls')),
    path('', include('user.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'blog'

urlpatterns = [
    path('submit-post/', SubmitBlogPost, name='submit-post'),
    path('blog/', PostListView.as_view(), name='blog'),
    path('blog/<int:pk>', PostDetailsView.as_view(),
         name='blog-single'),

    path('blog/<int:pk>/delete', PostDeleteView.as_view(), name='blog-delete'),
    path('blog/<int:pk>/update', PostUpdateView.as_view(), name='blog-update'),
    path('blog/<int:id>/addcomment', AddPostCommentView, name='blog-comment'),
    path("search", SearchBlog, name='search'),
    path('archive/', BlogIndexView, name='archive'),
]

core/urls.py
from django.urls import path
from .views import HomePageView, FaqPageView, AboutUsPageView, ContacUsView, SendContactMessageView, NewsLetterSubscribe

app_name = 'core'

urlpatterns = [
    path('', HomePageView, name='home'),
    path('faq/', FaqPageView, name='faq'),
    path('about/', AboutUsPageView, name='about'),
    path('contacts/', ContacUsView, name='contacts'),
    path('contacts/sent', SendContactMessageView, name='send-contact-message'),
    path('subscribe', NewsLetterSubscribe, name='subscribe'),

]

recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


app_name = 'recipes'
urlpatterns = [
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('recipes/<int:pk>', RecipeDetailsView.as_view(), name='recipe-single'),
    path('recipes/<int:pk>/update', RecipeUpdateView.as_view(), name='recipe-update'),
    path('recipes/<int:pk>/steps/update', RecipeInstructionUpdateView.as_view(), name='recipe-steps-update'),
    path('recipes/<int:pk>/ingredient/update', RecipeIngredientsUpdateView.as_view(), name='recipe-ingredient-update'),
    path('recipes/<int:pk>/delete', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipes/<int:pk>/pdf/', ExportToPDFView.as_view(), name='recipe-pdf'),
    path('recipes/<int:id>/addcomment', AddCommentView, name='recipe-comment'),
    path('recipes/<int:id>/bookmark', BookmarkRecipeView, name='recipe-bookmark'),
    path('submit-recipe/', SubmitRecipeView, name='submit-recipe'),
    path('recipe-index/', RecipeIndexView, name='recipe-index'),
    path("search", SearchRecipes, name='search'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField


class HomePageLogo(models.Model):
    image = ResizedImageField(null=False, blank=False, size=[50, 50],
                              upload_to='logo/',
                              verbose_name='صورة الموقع الرئيسية')

    class Meta:
        verbose_name_plural = "logo"


class HomePageSlider(models.Model):
    image = ResizedImageField(null=False, blank=False, size=[700, 350],
                              upload_to='core/',
                              verbose_name='صور الصفحة الرئيسية')

    class Meta:
        verbose_name_plural = "slider"


# FAQ PAGE
class FaqShortBanner(models.Model):
    question = models.CharField(max_length=128, verbose_name="العنوان")
    answer = models.TextField(max_length=128, verbose_name="التفاصيل")

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "اقسام الاسئلة المكررة"



# FAQ PAGE
class FaqQuestionBanner(models.Model):
    question = models.CharField(max_length=128, verbose_name="العنوان")
    answer = models.TextField(max_length=128, verbose_name="التفاصيل")

    def __str__(self):
        return self.question

    class Meta:
        verbose_name_plural = "الاسئلة المكررة"


# About us
class AboutUsParagraph(models.Model):
    title = models.CharField(max_length=128, verbose_name="العنوان")
    descreption = models.TextField(verbose_name="التفاصيل", max_length=1024)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "فقرات الكتابة - معلومات عنا"



# About US page
class AboutUsCard(models.Model):
    image = ResizedImageField(null=False, blank=False, size=[150,150],
                              upload_to='core/',
                              verbose_name='الصورة')
    name = models.CharField(max_length=128, verbose_name="الاسم")
    position = models.CharField(max_length=128, verbose_name="الوظيفة")
    more_info = models.CharField(max_length=256, verbose_name="تفاصيل اخري")
    facebook_url = models.URLField(
        max_length=128, verbose_name="الملف الشخصي علي فيسبوك", blank=True)
    twitter_url = models.URLField(
        max_length=128, verbose_name="الملف الشخصي علي تويتر", blank=True)
    instgram_url = models.URLField(
        max_length=128, verbose_name="الملف الشخصي علي انستجرام", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "كروت التعريف - معلومات عنا"


class ContactMessages(models.Model):
    email = models.EmailField(max_length=128, verbose_name="البريد الالكتروني")
    address = models.CharField(max_length=128, verbose_name="العنوان")
    message = models.TextField(max_length=1024, verbose_name="الرسالة")

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "رسائل الزوار - اتصل بنا"


class ContactParagraph(models.Model):
    title = models.CharField(max_length=128, verbose_name="العنوان")
    descreption = models.TextField(verbose_name="التفاصيل", max_length=1024)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "فقرات الكتابة - اتصل بنا"


class ContactLocation(models.Model):
    locationURL = models.TextField(
        verbose_name="رابط العنوان", max_length=1024)

    def __str__(self):
        return self.locationURL

    class Meta:
        verbose_name_plural = "العنوان - اتصل بنا"


class ContactSideParagraph(models.Model):
    title = models.CharField(max_length=128, verbose_name="العنوان")
    descreption = models.TextField(verbose_name="التفاصيل", max_length=1024)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "فقرات الكتابة الجانبية - اتصل بنا"


class NewsLetterEmail(models.Model):
    email = models.EmailField(verbose_name="البريد الالكتروني")

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "المشتركين باخر التحديثات"

core/views.py
from django.shortcuts import render, redirect

from .models import (AboutUsCard, AboutUsParagraph, ContactParagraph,
                     ContactSideParagraph, FaqQuestionBanner, FaqShortBanner,
                     ContactLocation, ContactMessages, NewsLetterEmail, HomePageSlider, HomePageLogo)

from recipes.models import RecipeCategory, Recipe
from blog.models import Post
from user.models import Profile


def HomePageView(request):
    context = {}
    logo = HomePageLogo.objects.all().order_by('-id')[:1]
    context['logo'] = [*logo]
    images = HomePageSlider.objects.all()
    context['images'] = [*images]

    data = {}
    categories = RecipeCategory.objects.all()[:4]
    for category in categories:
        recipes = Recipe.objects.filter(category=category)[:3]
        data[category] = [*recipes]
    context["echoice"] = data

    recent_posts_qs = Post.objects.all().order_by('date_created')[:4]
    context['recent_posts'] = [*recent_posts_qs]

    recent_recipes_qs = Recipe.objects.all().order_by('date_created')[:8]
    context['recent_recipes'] = [*recent_recipes_qs]

    profiles_qs = Profile.objects.all()[:7]
    context['editors'] = [*profiles_qs]

    return render(request, 'core/home.html', context)


def FaqPageView(request):
    context = {}
    context['shortbanners'] = FaqShortBanner.objects.all()
    context['questions'] = FaqQuestionBanner.objects.all()
    return render(request, 'core/faq.html', context)


def AboutUsPageView(request):
    context = {}
    context['paragraphs'] = AboutUsParagraph.objects.all()
    context['cards'] = AboutUsCard.objects.all()
    return render(request, 'core/about.html', context)


def ContacUsView(request):
    context = {}
    context['paragraphs'] = ContactParagraph.objects.all()
    context['side_paragraphs'] = ContactSideParagraph.objects.all()
    context['location'] = ContactLocation.objects.all()[:1]
    return render(request, 'core/contact.html', context)


def SendContactMessageView(request):
    address = request.POST['address']
    email = request.POST['email']
    message = request.POST['message']
    ContactMessages.objects.create(
        email=email, address=address, message=message)
    return redirect("core:home")


def NewsLetterSubscribe(request):
    email = request.POST['EMAIL']
    NewsLetterEmail.objects.create(email=email)
    return redirect("core:home")

core/templates/core/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="head-title">
    <div class="container">
        <h2 class="page-title">معلومات عنا</h2>
    </div><!-- end container -->
</div><!-- end head-title -->
<div id="main">
    <div class="container">
        <div id="primary" class="content-area fullwidth">
            <div id="content" class="site-content">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="about-desc">
                            {% for item in paragraphs %}
                            <p><strong>{{item.title}}</strong></p>
                            <p>{{item.descreption}}</p>
                            {% endfor %}
                        </div><!-- end team desc -->
                    </div><!-- end col -->
                </div><!-- end row -->
                <div class="row">
                    {% for item in cards %}
                    <div class="col-md-4">
                        <div class="team-col">
                            <figure>
                                <img src="{{item.image.url}}" height="150px" width="150px">
                            </figure>
                            <p class="team-name">{{item.name}}</p>
                            <span class="team-tag">{{item.position}}</span>
                            <p class="team-desc">{{item.more_info}}</p>
                            <div class="team-media">
                                <a href="{{item.twitter_url}}"><i class="fab fa-twitter"></i></a>
                                <a href="{{item.facebook_url}}"><i class="fab fa-facebook-square"></i></a>
                                <a href="{{item.instgram_url}}"><i class="fab fa-instagram"></i></a>
                            </div><!-- end team media -->
                        </div><!-- end team col -->
                    </div><!-- end col -->
                    {% endfor %}

                </div><!-- end row -->

            </div><!-- end content -->
        </div><!-- end primary -->

    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}

core/templates/core/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="head-title">
    <div class="container">
        <h2 class="page-title">اتصل بنا</h2>
    </div><!-- end container -->
</div><!-- end head-title -->

<div id="main">
    <div class="container">

        <div id="primary" class="content-area">
            <div id="content" class="site-content">

                <div class="row no-gutters">


                    <div class="col-md-8">
                        <div class="contact-form">
                            <h3>اترك لنا رسالتك هنا</h3>
                            <p>الرجاء ملء جميع البيانات وسوف نقوم بالرد عليك في اقرب وقت</p>
                            <form action="{% url 'core:send-contact-message' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="inputAddress">العنوان</label>
                                        <input type="text" class="form-control" id="inputAddress" name="address"
                                            placeholder="32 شارع الشيخ زايد" required>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="inputEmail">البريد الالكتروني</label>
                                        <input type="email" class="form-control" name="email" id="inputEmail"
                                            placeholder="البريد الالكتروني" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <label for="messageTextarea">رسالتك</label>
                                    <textarea class="form-control" id="messageTextarea" name="message" rows="10"
                                        required></textarea>
                                </div><!-- end form-row -->
                                <div class="form-button">
                                    <button type="submit" class="btn btn-primary">ارسال الرسالة</button>
                                </div>
                            </form>
                        </div><!-- end contact-form -->
                    </div><!-- end col -->
                    {% for item in location %}
                    <div class="col-md-4">
                        <div class="gmap entry-media">
                            <iframe src="{{item.locationURL}}" width="620" height="510"></iframe>
                        </div><!-- end entry-media -->
                    </div><!-- end col -->
                    {% endfor %}
                </div><!-- end row -->

                <div class="row-space"></div>

                <div class="row justify-content-between">
                    {% for item in paragraphs %}
                    <div class="col-md-8">
                        <h2>{{item.title}}</h2>
                        <p>{{item.descreption}}</p>
                    </div>
                    {% endfor %}

                    {% for item in side_paragraphs %}
                    <div class="col-md-4">
                        <p><strong>{{item.title}}</strong></p>
                        <p>{{item.descreption}}</p>
                    </div><!-- end col -->
                    {% endfor %}


                </div><!-- end row -->

            </div><!-- end content -->
        </div><!-- end primary -->

    </div><!-- end container -->
</div><!-- end main -->

{% endblock %}

core/templates/core/faq.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div class="head-title">
            <div class="container">
                <h2 class="page-title">أسئلة متكررة</h2>
            </div><!-- end container -->
        </div><!-- end head-title -->

        <div id="main">
            <div class="container">

                <div class="faq-content">
                    <div class="row">
                      
                        {% for banner in shortbanners %}
                        <div class="col-6 col-md-4">
                            <span>
                                <i class="fas fa-user-check"></i>
                            </span>
                            <h3>{{banner.question}}</h3>
                            <p>{{banner.answer}}</p>
                        </div><!-- end col -->
                        {% endfor %}
                    </div><!-- end row -->

                    <div class="row-space"></div>

                    <div class="row justify-content-center">
                        <div class="col-12 col-md-8">
                            <div id="accordion">
                              {% for item in questions %}
                              <div class="card">
                                <div class="card-header" id="headingThree">
                                  <h5 class="mb-0">
                                    <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                      {{item.question}}
                                    </button>
                                  </h5>
                                </div>
                                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                                  <div class="card-body">
                                    {{item.answer}}
                                  </div>
                                </div>
                              </div><!-- end card -->
                              {% endfor %}

                            </div><!-- end accordion -->
                        </div><!-- end col -->

                    </div><!-- end row -->
                </div><!-- end faq content -->

            </div><!-- end container -->
        </div><!-- end main -->

{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}
{% load static %}


{% block logo %}
    
    {% if logo %}
        {% for item in logo %}
        <div class="site-branding navbar-brand">
            <a href="{% url 'core:home' %}"><img src="{{item.image.url}}" 
                alt="Food Recipe Web Template" title="أطايب"></a>
        </div><!-- end logo -->  
        {% endfor %}  
    {% else %}
        <div class="site-branding navbar-brand">
            <a href="{% url 'core:home' %}"><img src="{% static 'images/atayeb_logo_300.png' %}" height="50px"
                alt="Food Recipe Web Template" title="أطايب"></a>
        </div><!-- end logo -->
    {% endif %}
{% endblock %}                    

{% block content %}

    <!-- SLIDER SECTION -->
    <div class="owl-carousel owl-theme">
        {% if images %}
            {% for item in images %}
            <div class="item">
                <img src="{{item.image.url}}" alt="slide 1">
            </div><!-- end item -->
            {% endfor %}
        {% else %}
            <div class="item">
                <img src="{% static 'images/assets/slide-13.png' %}" alt="slide 1">
                <div class="caption">
                    <h2 class="animated bounce">أشهى الأطباق المنزلية</h2>
                    <button class="btn btn-primary">EXPLORE NOW</button>
                </div> 
            </div><!-- end item -->
        {% endif %}

    </div><!-- end owl-carousel -->

    <div class="choice-section">
        {% if echoice %}
            <div class="container">
                <div class="section-title">
                    <h3>اختيار المحررين</h3>
                </div><!-- end section-title -->
                <hr>
                <div class="row">
                    {% for key, value in echoice.items %}
                    <div class="col-6 col-md-3">
                        <div class="big-bone">
                            <a href="#" class="figure-caption">
                                <div class="caption-inner">
                                    <span>{{value|length}} وصفات</span>
                                    <p>{{key}}</p>
                                </div>
                            </a>
                            <figure><img src="{% static 'images/content/food-l.png' %}" alt="food l"></figure>
                        </div>
                    </div>
                    {% endfor %}
                </div><!-- end row -->

            </div><!-- end container -->
        {% else %}
            <div class="container">
                <div class="section-title">
                    <h3>اختيار المحررين</h3>
                </div><!-- end section-title -->
                <div class="row">
                    <div class="col-6 col-md-3">
                    <div class="big-bone">
                        <a href="#" class="figure-caption">
                            <div class="caption-inner">
                                <p>Sweets</p>
                                <span>0 Recipes</span>
                            </div>
                        </a>
                        <figure><img src="{% static 'images/content/food-l.png' %}" alt="food l"></figure>
                    </div>
                    </div><!-- end col -->
                    <div class="col-6 col-md-3">
                    <div class="big-bone">
                    <a href="#" class="figure-caption">
                        <div class="caption-inner">
                            <p>Sweets</p>
                            <span>0 Recipes</span>
                        </div>
                    </a>
                    <figure><img src="{% static 'images/content/food-l.png' %}" alt="food l"></figure>
                </div>
                    </div><!-- end col -->
                    <div class="col-6 col-md-3">
                <div class="big-bone">
                    <a href="#" class="figure-caption">
                        <div class="caption-inner">
                            <p>Sweets</p>
                            <span>0 Recipes</span>
                        </div>
                    </a>
                    <figure><img src="{% static 'images/content/food-l.png' %}" alt="food l"></figure>
                </div>
                    </div><!-- end col -->
                    <div class="col-6 col-md-3">
                <div class="big-bone">
                    <a href="#" class="figure-caption">
                        <div class="caption-inner">
                            <p>Sweets</p>
                            <span>0 Recipes</span>
                        </div>
                    </a>
                    <figure><img src="{% static 'images/content/food-l.png' %}" alt="food l"></figure>
                </div>
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->
        {% endif %}
    </div><!-- end editor-section -->

    <div class="features-section parallax-bg">
        <div class="container">
            <div class="section-title">
                <h3>مميزات موقعنا</h3>
            </div><!-- end section-title -->
            <div class="row">
                <div class="col-md-4">
                    <div class="inner">
                        <span class="fitcon"><i class="fas fa-chart-line"></i></span>
                        <h4>الحقائق الغذائية</h4>
                        <p>نوفر الحقائق الغذائية الخاصة بكل وصفة من وصفاتنا</p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="inner">
                        <span class="fitcon"><i class="far fa-clock"></i></span>
                        <h4>وقت التحضير</h4>
                        <p>كل وصفة من وصفاتنا تحتوي وقت التحضير الخاص بها</p>
                    </div>
                </div><!-- end col -->
                <div class="col-md-4">
                    <div class="inner">
                        <span class="fitcon"><i class="fas fa-user-friends"></i></span>
                        <h4>الاشتراك</h4>
                        <p>سهولة الاشتراك في موقعنا</p>
                    </div>
                </div><!-- end col -->
            </div><!-- end row -->
        </div><!-- end container -->
    </div><!-- end features -->

    <div class="recipes-section">
        {% if recent_recipes %}
            <div class="container">
                <div class="section-title">
                    <h3>وصفات خاصة</h3>
                </div><!-- end section-title -->
                
                <div class="row">
                    {% for recipe in recent_recipes%}
                        <div class="col-6 col-md-3">
                            <div class="recipe-thumb">
                                <img src="{{recipe.image.url}}" width="250px" height="200px" alt="Recipe Image">
                                <a href="{% url 'recipes:recipe-single'  recipe.id %}" class="view-recipe">عرض الوصفة</a>
                            </div>
                            <div class="recipe-desc">
                                <h2 class="recipe-title">
                                    <a href="{% url 'recipes:recipe-single'  recipe.id %}"> {{recipe.name}} </a>
                                </h2>
                                <p><em> بواسطة {{recipe.author}} </em></p>
                                <span><i class="fas fa-clock"></i> {{recipe.prep_time}} دقيقة </span>
                            </div><!-- end recipe-desc -->
                        </div><!-- end col -->
                    {% endfor %}
                </div><!-- end row -->

                <div class="row">
                    <div class="centered">
                        <a href="{% url 'recipes:recipes' %}" class="btn btn-line">اعرض كل الوصفات</a>
                    </div><!-- end centered -->
                </div><!-- end row -->   

            </div><!-- end container -->
        {% else %}
            <div class="row justify-content-center">
                <h2>لا توجد وصفات متاحة حاليا .. نعمل علي اضافة المزيد قريبا ! </h2>
            </div>
        {% endif%}
    </div><!-- end recipes -->

    <div class="editor-section">
        {% if editors %}
        <div class="container">
            <div class="section-title">
                <h3>محرري أطايب</h3>
            </div><!-- end section-title -->
            <div class="row justify-content-center">
                {% for profile in editors %}
                    <div class="col-6 col-md-2">
                        <div class="author-col">
                            <figure class="auth-ava">
                                {% if profile.image %}
                                    <img src="{{profile.image.url}}" width="100px" height="100px" alt="Avatar">
                                {% else %}
                                    <img src="{% static 'images/content/ava-1.png' %}" width="100px" height="100px" alt="Avatar">
                                {% endif %}
                            </figure>
                            <h4>{{profile.user.username}}</h4>
                        </div><!-- end author-col -->
                    </div><!-- end col -->
                {% endfor %}
            </div><!-- end row -->
        </div><!-- end container -->
        {% endif %}
    </div><!-- end editor-section -->

    <div class="blog-section">
        {% if recent_posts %}
            <div class="container">
                <div class="section-title">
                    <h3>أحدث المنشورات </h3>
                </div><!-- end section-title -->
                <div class="row">
                    {% for post in recent_posts %}
                        <div class="col-6 col-md-3 blog-list">
                            <figure class="blog-thumb">
                                {% if post.image %}
                                    <img src="{{post.image.url}}" height="180px" width="270px" alt="blog">
                                {% else %}
                                    <img src="{% static 'images/content/blog-1.png' %}" alt="blog">
                                {% endif %}
                            </figure>
                            <div class="entry-header">
                                <h2 class="post-title entry-title">
                                    <a href="{% url 'blog:blog-single'  post.id %}">{{post.title}}</a>
                                </h2>
                            </div><!-- end entry-header -->
                            <div class="post-meta">
                                <time class="published" datetime="2019-12-22"
                                title="December 22, 2019 - 21:12 pm">{{post.date_created|date}} </time>
                                <div class="cat"><a href="#">{{post.category}}</a></div>
                            </div>
                        </div><!-- end col -->
                    {% endfor %}
                </div><!-- end row -->
            </div><!-- end container -->
        {% endif %}
    </div><!-- end blog-section -->


{% endblock %}